-- 手当カラムを追加（洗濯・仕切・宿泊）
ALTER TABLE report_staff_entries
ADD COLUMN IF NOT EXISTS is_laundry BOOLEAN DEFAULT FALSE COMMENT '洗濯',
ADD COLUMN IF NOT EXISTS is_partition BOOLEAN DEFAULT FALSE COMMENT '仕切',
ADD COLUMN IF NOT EXISTS is_accommodation BOOLEAN DEFAULT FALSE COMMENT '宿泊';

